<article class="news">
  <h3 class="news__title">News</h3>

  <!--
  <div
    class="fb-page"
    data-href="https://www.facebook.com/kissomlyo"
    data-adapt-container-width="false"
    data-height="1621"
    data-width="340"
    data-small-header="true"
    data-hide-cover="true"
    data-show-facepile="false"
    data-show-posts="true">
  </div>
  -->

  <div class="news__body" data-url="{{ fb.url }}"></div>


</article>
